### ISSUE TITLE
Default Quantity should 1

### ISSUE THREAD

**Issue by sarahproof** [araneforseti/grocery-app#56]
**Describe the bug**
When creating a new item, it is automatically added to the grocery list, however the quantity is set to 0.

**To Reproduce**
1. Go to 'Item List'
2. Click on 'Create New Item'
3. Fill out howeverr
4. See item added to grocery list with quantity 0

**Expected behavior**
Quantity should be 1

**Comment by Ohior** [comment]
What line or file did you think the bug is

**Comment by araneforseti** [comment]
There's a couple options I was looking at for fixing it:
- Default constructor for Item is 0, so just setting that to 1 would get the behavior looking for.
- Arguably it can also be fixed via updating ItemRepo's createItem to accept a quantity and have the create set it to 1.
- Final option is to not have created items added to the grocery list by default (which would make the 0 default correct), but I don't think this would be a good experience since while using the app, I've only been creating items when I want them on the grocery list.

Of the three, the first option is easiest and shouldn't have side effects. I can't think of a reason to keep the 0.
